# Based on: https://github.com/clap-rs/clap/blob/master/.github/workflows/ci.yml

name: CI

permissions:
  contents: read

on:
  pull_request:
  push:

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

jobs:
  test:
    name: Test
    strategy:
      matrix:
        build: [linux]
        include:
          - build: linux
            os: ubuntu-latest
            rust: "stable"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Install Rust
        uses: dtolnay/rust-toolchain@beta
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@v2
      - name: Install liburing
        run: |
          sudo apt-get update
          sudo apt-get install -y liburing-dev
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-about
      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.x
      - name: Run CI
        run: ./scripts/ci/all
      - name: Test
        run: cargo test
